
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const ISARAYAN_LOGIN_SUCCESS = "ISARAYAN_LOGIN_SUCCESS"
export const ISVEREN_LOGIN_SUCCESS = "ISVEREN_LOGIN_SUCCESS"
export const ISARAYAN_LOGIN_FAILURE = "ISARAYAN_LOGIN_FAILURE"
export const ISVEREN_LOGIN_FAILURE = "ISVEREN_LOGIN_FAILURE"
export const LOGOUT_USER = "LOGOUT_USER"
